apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  namespace:  myapp
  name: myapp-job
  labels:
    name: myapp-job
    role: job
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  suspend: false
  jobTemplate:
    metadata:
      name: myapp-job
      labels:
        job: myapp-job
        role: job
    spec:
      template:
        metadata:
          name: myapp-job
          labels:
            job: myapp-job
            role: job
        spec:
          hostname: scheduler
          containers:
          - name: job
            image: quay.io/koudaiii/myapp:latest
            imagePullPolicy: Always
            command:
              - "/bin/bash"
              - "-l"
              - "-c"
              - "bundle exec rails hello || true"
            env:
             - name: "RAILS_SERVE_STATIC_FILES"
               value: "enabled"
             - name: "RAILS_LOG_TO_STDOUT"
               value: "enabled"
            envFrom:
            - secretRef:
                name: dotenv
          restartPolicy: Never
