apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: myapp
  labels:
    name: postgres
    role: db
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    name: postgres
    role: db
