#!/usr/bin/env bash

set -eu
set -o pipefail

if [ "$TRAVIS_BRANCH" == "master" ]; then
  echo "Deploy ${REPO}:${TAG_COMMITTAG} in production"
#  ./kops export kubecfg --name $K8S_PROD_CLUSTER
else
  echo "Deploy ${REPO}:${TAG_COMMIT} in qa"
#  ./kops export kubecfg --name $K8S_QA_CLUSTER
fi

# ./kubectl set image deployment/${DEPLOYMENT_NAME} rails=${REPO}:${TAG_COMMIT} --namespace=${NAMESPACE} --record
