apiVersion: v1
kind: Secret
metadata:
  name: dotenv
  namespace: myapp
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9jb2RlOnppbmVAcG9zdGdyZXM6NTQzMi9teWFwcA==
  RACK_ENV: cHJvZHVjdGlvbg==
  RAILS_ENV: cHJvZHVjdGlvbg==
  SECRET_KEY_BASE: OTJhNDUzZDk5NjdjYmFjYjAzYzI2ZDNhNDdiY2ZkMmMxYzU0ZmIwZjZmMDViNTYwMmI5MTZlYzVlZTBiZTIzZTE2YjkwYjVkZjdmZGM3ZmM0OWM0ZGE5ZWY4MzVmYjEzNWRlYWQzODM5MmNlM2NmNmU1ZjZiNjNhMzkzYzQxMGE=
