apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: myapp
  labels:
    name: myapp
    role: web
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
  selector:
    name: myapp
    role: web
  type: LoadBalancer
